app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Sloppy2ndz Routes
|--------------------------------------------------------------------------
|
*/

Route::get('/', function () {
    return 'Sloppy2ndz API v1';
});

/**
 * Admin Routes
 */
Route::group(['prefix' => 'admin'], function () {
    /*
     * before authorization
     */
    Route::get('/', [
        'as' => 'login',
        'uses' => 'AuthController@login'
    ]);
    Route::post('/', 'AuthController@processLogin');

    /*
     * after authorization
     */
    Route::get('dashboard', [
        'as' => 'dashboard',
        'uses' => 'AdminController@dashboard',
    ]);
    Route::get('logout', [
        'as' => 'logout',
        'uses' => 'AuthController@logout',
    ]);

    // Users
    Route::resource('users', 'UsersController');

    // Products
    Route::resource('products', 'ProductsController');
});

/**
 * API Routes
 * Version: 1.0
 */
Route::group(['prefix' => 'api/v1'], function () {
    Route::post('register', 'ApiController@register');
    Route::post('login', 'ApiController@login');
    Route::post('login/facebook', 'ApiController@loginViaFacebook');
    Route::post('login/instagram', 'ApiController@loginViaInstagram');

    // routes for authenticated users only
    Route::group(['middleware' => 'jwt.auth'], function () {
        // Settings
        Route::post('edit-profile', 'ApiController@editProfile');
        Route::post('edit-billing', 'ApiController@editBilling');
        Route::post('edit-paypal', 'ApiController@editPaypal');
        Route::post('edit-bank', 'ApiController@editBank');
        Route::post('edit-currency', 'ApiController@editCurrency');

        // Profile
        Route::get('profile', 'ApiController@userProfile');

        // Product Category
        Route::post('add-category', 'ApiController@addCategory');
        Route::get('categories', 'ApiController@listCategories');
        Route::get('category', 'ApiController@categoryDetails');

        // Product
        Route::post('add-product', 'ApiController@addProduct');
        Route::get('product', 'ApiController@productDetails');
        Route::post('add-comment', 'ApiController@addComment');
        Route::get('comments', 'ApiController@listComments');
    });
});

resources/views/partials/_footer.blade.php
<div class="page-footer">
    <div class="page-footer-inner">
        Copyright &copy; {{ $site_title }} {{ date('Y') }}
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>

resources/views/partials/_header.blade.php
<div class="page-header navbar navbar-fixed-top">
    <div class="page-header-inner ">

        <div class="page-logo">
            <a href="{{ route('dashboard') }}">
                Sloppy2ndz
            </a>

            <div class="menu-toggler sidebar-toggler">
            </div>
        </div>

        <div class="page-top">

            <form class="search-form search-form-expanded" action="" method="post">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." name="query">
                        <span class="input-group-btn">
                            <a href="javascript:;" class="btn submit">
                                <i class="icon-magnifier"></i>
                            </a>
                        </span>
                </div>
            </form>

            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                           data-close-others="true">
                            <i class="icon-bell"></i>
                            <span class="badge badge-default"> 1 </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="external">
                                <h3>
                                    <span class="bold">1 pending</span> notifications</h3>
                                <a href="{{ url('/') }}">view all</a>
                            </li>
                            <li>
                                <ul class="dropdown-menu-list scroller" data-handle-color="#637283">
                                    <li>
                                        <a href="javascript:;">
                                            <span class="time">just now</span>
                                            <span class="details">
                                                <span class="label label-sm label-icon label-success">
                                                    <i class="fa fa-plus"></i>
                                                </span> New user registered.
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>

                    <li class="dropdown dropdown-user">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                           data-close-others="true">
                            <img alt="" class="img-circle"
                                 src="{{ asset('assets/layouts/layout2/img/avatar3_small.jpg') }}"/>
                            <span class="username username-hide-on-mobile"> Nick </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-default">
                            <li>
                                <a href="javascript:;">
                                    <i class="icon-user"></i> My Profile </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <i class="icon-envelope-open"></i> My Inbox
                                    <span class="badge badge-danger"> 3 </span>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="{{ route('logout') }}">
                                    <i class="icon-key"></i> Log Out </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>

resources/views/partials/_sidebar.blade.php
<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        <ul class="page-sidebar-menu  page-header-fixed page-sidebar-menu-hover-submenu " data-keep-expanded="false"
            data-auto-scroll="true" data-slide-speed="200">
            <li class="nav-item start active open">
                <a href="{{ route('dashboard') }}" class="nav-link nav-toggle">
                    <i class="icon-home"></i>
                    <span class="title">Dashboard</span>
                    <span class="selected"></span>
                    <span class="arrow open"></span>
                </a>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-briefcase"></i>
                    <span class="title">Category</span>
                    <span class="arrow"></span>
                </a>
            </li>
            <li class="nav-item  ">
                <a href="{{ route('admin.products.index') }}" class="nav-link nav-toggle">
                    <i class="icon-diamond"></i>
                    <span class="title">Product</span>
                    <span class="arrow"></span>
                </a>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-basket-loaded"></i>
                    <span class="title">Sell</span>
                    <span class="arrow"></span>
                </a>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-calculator"></i>
                    <span class="title">Transaction</span>
                    <span class="arrow"></span>
                </a>
            </li>
            <li class="nav-item  ">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-bar-chart"></i>
                    <span class="title">Festival</span>
                    <span class="arrow"></span>
                </a>
            </li>
            <li class="nav-item  ">
                <a href="{{ route('admin.users.index') }}" class="nav-link nav-toggle">
                    <i class="icon-users"></i>
                    <span class="title">User</span>
                    <span class="arrow"></span>
                </a>
            </li>
            <li class="nav-item">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-notebook"></i>
                    <span class="title">Report</span>
                    <span class="arrow "></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item">
                        <a href="javascript:;" class="nav-link nav-toggle">
                            <i class="icon-settings"></i> Details
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="icon-bar-chart"></i> Search
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
</div>